
name: TestMavenBuild

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build maven project
        run: mvn package -Dmaven.test.skip=true --file pom.xml
